import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="bg-gray-800 text-white py-4 mt-8">
          <div className="container mx-auto text-center">
            <p className="text-sm">Helpful Interactive Websites for Music Theory:</p>
            <ul className="list-none mt-2">
              <li><a href="https://www.musictheory.net/" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">musictheory.net</a></li>
              <li><a href="https://www.teoria.com/" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">teoria.com</a></li>
              <li><a href="https://www.8notes.com/" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">8notes.com</a></li>
              <li><a href="https://www.musictheoryacademy.com/" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">Music Theory Academy</a></li>
            </ul>
          </div>
        </footer>
      </body>
    </html>
  );
}
