import type { Unit } from '@/app/utils/curriculumData';

export const CURRICULUM_RO: Unit[] = [
    {
        id: 'foundations',
        title: 'Bazele Înălțimii și Intervalelor',
        description: 'Începe de aici: ce este înălțimea sunetului, cum se numesc intervalele și cum să începi să le recunoști după ureche.',
        lessons: [
            {
                id: 'pitch-basics',
                title: 'Ce Este Înălțimea Sunetului?',
                summary: 'Semitonuri, tonuri întregi și octava.',
                content: [
                    'Înălțimea sunetului reprezintă cât de sus sau de jos sună o notă. Pe pian sau chitară, cel mai mic pas posibil dintre două sunete se numește semiton (sau semi-pas) — distanța de la orice clape la clapa imediat următoare, albă sau neagră.',
                    'Două semitonuri formează un ton întreg. Stivuiește doisprezece semitonuri la rând și ajungi la o octavă: același nume de notă din nou, dar vibrând la exact dublul (sau jumătatea) frecvenței. Acel ciclu de 12 semitonuri — scala cromatică — este setul complet de sunete din care e construită muzica occidentală, înainte de a se repeta.',
                    'Tot ce urmează în acest curriculum — intervale, game, acorduri — sunt doar moduri diferite de a selecta și combina note din acel ciclu de 12 sunete.',
                ],
                quiz: [
                    {
                        question: 'Câte semitonuri are o octavă?',
                        choices: ['7', '8', '12', '10'],
                        correctIndex: 2,
                        explanation: 'Scala cromatică are 12 sunete distincte înainte ca tiparul să se repete o octavă mai sus.',
                    },
                    {
                        question: 'Cum se numește cea mai mică distanță dintre două sunete?',
                        choices: ['Un ton întreg', 'O octavă', 'Un semiton (semi-pas)', 'O treaptă a gamei'],
                        correctIndex: 2,
                        explanation: 'Semitonul — distanța de la orice clapă la cea imediat următoare — este cel mai mic pas standard în muzica occidentală.',
                    },
                    {
                        question: 'Câte semitonuri formează un ton întreg?',
                        choices: ['1', '2', '3', '4'],
                        correctIndex: 1,
                        explanation: 'Un ton întreg este format din două semitonuri.',
                    },
                    {
                        question: 'Dacă o notă vibrează la 440 Hz, care este frecvența aceleiași note cu o octavă mai sus?',
                        choices: ['450 Hz', '660 Hz', '880 Hz', '220 Hz'],
                        correctIndex: 2,
                        explanation: 'O octavă în sus dublează frecvența: 440 Hz × 2 = 880 Hz.',
                    },
                ],
            },
            {
                id: 'interval-names',
                title: 'Denumirea Intervalelor',
                summary: 'Cum primesc intervalele numerele și calitățile lor.',
                content: [
                    'Un interval este pur și simplu distanța dintre două note. Intervalele primesc un număr în funcție de câte nume de note cuprind (de la C la E cuprinde C-D-E, trei litere, deci este un fel de „terță") și o calitate (major, minor sau just) care precizează numărul exact de semitonuri.',
                    'Cele mai frecvente intervale, de la cel mai mic la cel mai mare în cadrul unei octave: secundă mică (1 semiton), secundă mare (2), terță mică (3), terță mare (4), cvartă justă (5), cvintă justă (7), sextă mică (8), sextă mare (9), septimă mică (10), septimă mare (11) și octava însăși (12).',
                    'Cvartele și cvintele juste nu vin în versiuni „major/minor" în practica standard — sunt pur și simplu juste, deoarece sună stabil și consonant indiferent de context. Toate celelalte se grupează câte două: major (mai mare) sau minor (cu un semiton mai mic).',
                ],
                practice: { category: 'intervals', difficulty: 'easy', label: 'Intervale · Ușor' },
                quiz: [
                    {
                        question: 'Câte semitonuri are o terță mare?',
                        choices: ['3', '4', '5', '2'],
                        correctIndex: 1,
                        explanation: 'O terță mare cuprinde 4 semitonuri, de exemplu C la E.',
                    },
                    {
                        question: 'Ce interval are 7 semitonuri?',
                        choices: ['Sextă mare', 'Cvartă justă', 'Cvintă justă', 'Septimă mică'],
                        correctIndex: 2,
                        explanation: 'Cvinta justă are 7 semitonuri — cel mai stabil interval după octavă.',
                    },
                    {
                        question: 'Ce calitate de interval NU are pereche major/minor?',
                        choices: ['Terțe', 'Sexte', 'Cvarte și cvinte', 'Septime'],
                        correctIndex: 2,
                        explanation: 'Cvartele și cvintele juste sunt pur și simplu „juste" — nu vin în versiuni major/minor ca secundele, terțele, sextele și septimele.',
                    },
                    {
                        question: 'De la C la F cuprinde câte nume de note (C, D, E, F) și cum se numește intervalul?',
                        choices: ['3 litere — o terță', '4 litere — o cvartă', '5 litere — o cvintă', '4 litere — o cvintă'],
                        correctIndex: 1,
                        explanation: 'C-D-E-F sunt 4 nume de note, deci C la F este un fel de cvartă — mai precis o cvartă justă (5 semitonuri).',
                    },
                ],
            },
            {
                id: 'interval-ear-training',
                title: 'Antrenamentul Urechii pentru Intervale',
                summary: 'Trucuri practice pentru recunoașterea intervalelor după sunet.',
                content: [
                    'A citi numele intervalelor este un lucru; a le recunoaște după ureche este abilitatea reală. Cel mai rapid mod este să ancorezi fiecare interval la o melodie pe care o știi deja și care începe cu exact acel salt.',
                    'Câteva ancore frecvente: secunda mică sună ca tema din „Jaws"; secunda mare deschide „Happy Birthday"; terța mică deschide „Greensleeves"; terța mare deschide „Kumbaya"; cvarta justă deschide „Vine Mireasa" și „Amazing Grace"; cvinta justă deschide fanfara principală din „Star Wars" și „Twinkle, Twinkle, Little Star"; sexta mare deschide „My Bonnie Lies Over the Ocean".',
                    'Când auzi două note în exercițiul de Antrenament Auditiv de mai jos, încearcă să cânți distanța înapoi și să o compari cu una din melodiile de referință înainte de a verifica variantele de răspuns.',
                ],
                practice: { category: 'intervals', difficulty: 'medium', label: 'Intervale · Mediu' },
                quiz: [
                    {
                        question: 'De ce este utilă asocierea intervalelor cu melodii familiare în antrenamentul auditiv?',
                        choices: [
                            'Înlocuiește necesitatea de a cunoaște numele intervalelor',
                            'Oferă urechii tale un punct de referință concret pentru comparație',
                            'Funcționează doar pentru intervale juste',
                            'Este utilă mai ales pentru ritm, nu pentru înălțime',
                        ],
                        correctIndex: 1,
                        explanation: 'O melodie familiară îți oferă o referință instantă pentru cum sună un interval, făcând legătura dintre teorie și recunoaștere.',
                    },
                    {
                        question: 'Ce este în general adevărat despre disonanța unui interval pe măsură ce se micșorează (se apropie de unison)?',
                        choices: [
                            'Intervalele mai mici, ca secunda mică, tind să sune mai tensionat/disonant',
                            'Intervalele mai mici sună întotdeauna mai consonant',
                            'Mărimea intervalului nu afectează consonanța',
                            'Numai intervalele majore pot suna disonant',
                        ],
                        correctIndex: 0,
                        explanation: 'Intervalele foarte strânse, ca secunda mică, se ciocnesc mai tare — de aceea sună tensionat, chiar baza din care vine amenințarea temei „Jaws".',
                    },
                    {
                        question: 'Cvinta justă și cvarta justă tind să sune:',
                        choices: ['Tensionat și nerezolvat', 'Deschis și stabil', 'Blues', 'Identic cu o terță mică'],
                        correctIndex: 1,
                        explanation: 'Intervalele juste sunt cele mai consonante și stabile, după octavă/unison.',
                    },
                    {
                        question: 'Ce ar trebui să faci când auzi un interval necunoscut înainte de a verifica variantele?',
                        choices: [
                            'Ghicești la întâmplare',
                            'Încearcă să fredonezi distanța și să o compari cu o melodie de referință',
                            'Presupui că e mereu o terță mare',
                            'Sari peste întrebare',
                        ],
                        correctIndex: 1,
                        explanation: 'Reproducerea activă a intervalului (chiar și mental) antrenează aceeași abilitate de recunoaștere pe care simpla ascultare nu o construiește la fel de repede.',
                    },
                ],
            },
            {
                id: 'compound-intervals',
                title: 'Intervale Compuse',
                summary: 'Ce sunt de fapt nonele, undecimele și terțdecimele.',
                content: [
                    'Odată ce depășești octava, intervalele primesc denumiri „compuse": o nonă este pur și simplu o octavă plus o secundă, o undecimă este o octavă plus o cvartă, iar o terțdecimă este o octavă plus o sextă. Relația de înălțime de bază (și sunetul ei) este aceeași ca intervalul simplu — o nonă are aceeași culoare ca o secundă, doar că întinsă mai departe.',
                    'Acestea apar constant în jazz și în vocingurile de acorduri extinse: un acord „C9" este un acord de dominantă septimă cu o nonă mare adăugată deasupra, ceea ce înseamnă de fapt „adaugă o secundă mare, cu o octavă mai sus."',
                    'Numărând semitonurile, relația devine evidentă: o secundă mare are 2 semitonuri, o nonă mare are 14 (2 + 12 pentru octava suplimentară). Aceeași logică se aplică pentru undecime (cvartă justă + 12) și terțdecime (sextă mare + 12).',
                ],
                practice: { category: 'intervals', difficulty: 'hard', label: 'Intervale · Greu' },
                quiz: [
                    {
                        question: 'O nonă este o octavă plus ce interval simplu?',
                        choices: ['O terță', 'O cvartă', 'O secundă', 'O sextă'],
                        correctIndex: 2,
                        explanation: 'O nonă = o octavă (8) + o secundă. Cifra „9" vine din 8 + 2 - 1 (partajând nota de la octavă).',
                    },
                    {
                        question: 'Câte semitonuri are o nonă mare?',
                        choices: ['9', '12', '14', '16'],
                        correctIndex: 2,
                        explanation: 'O secundă mare are 2 semitonuri; adaugă o octavă completă (12) pentru nona mare: 14 în total.',
                    },
                    {
                        question: 'O undecimă justă este o octavă plus ce interval?',
                        choices: ['O cvartă justă', 'O cvintă justă', 'O terță mare', 'O septimă mică'],
                        correctIndex: 0,
                        explanation: 'O undecimă = octavă + cvartă, exact cum o nonă este o octavă + secundă.',
                    },
                    {
                        question: 'De ce contează intervalele compuse în practică?',
                        choices: [
                            'Sună complet diferit față de echivalentele lor simple',
                            'Există doar în teorie, niciodată în acorduri reale',
                            'Descriu cum sunt construite acorduri extinse precum nonele și terțdecimele',
                            'Înlocuiesc necesitatea octavelor',
                        ],
                        correctIndex: 2,
                        explanation: 'Acordurile extinse (9, 11, 13) sunt denumite direct după aceste intervale compuse stivuite deasupra fundamentalei.',
                    },
                ],
            },
        ],
    },
    {
        id: 'scales-keys',
        title: 'Game și Armuri',
        description: 'Construiește gamele majore și minore dintr-o formulă, apoi conectează-le la armuri și cercul cvintelor.',
        lessons: [
            {
                id: 'major-scale',
                title: 'Formula Gamei Majore',
                summary: 'T-T-S-T-T-T-S și cele șapte trepte ale gamei.',
                content: [
                    'Fiecare gamă majoră urmează același tipar exact de tonuri (T) și semitonuri (S): T-T-S-T-T-T-S. Începe pe orice notă și aplică acel tipar, și vei obține o gamă majoră în acea tonalitate.',
                    'Pentru Do major: Do(T)Re(T)Mi(S)Fa(T)Sol(T)La(T)Si(S)Do — și deoarece aceasta aterizează numai pe taste albe, Do major nu are nici diezi, nici bemoli. Aplică aceeași formulă pornind de la Sol și obții Sol-La-Si-Do-Re-Mi-Fa♯-Sol: un diez, deoarece formula cere un ton întreg de la Mi la Fa♯, unde un Fa simplu ar fi doar un semiton distanță.',
                    'Cele șapte note sunt numerotate ca trepte ale gamei de la 1 la 7 (deseori numite do-re-mi-fa-sol-la-si). Treapta 1 este tonica — nota „acasă" după care se numește toată tonalitatea și spre care gravitează muzica.',
                ],
                practice: { category: 'scales', difficulty: 'easy', label: 'Game · Ușor' },
                quiz: [
                    {
                        question: 'Care este formula de tonuri/semitonuri pentru o gamă majoră?',
                        choices: ['T-S-T-T-S-T-T', 'T-T-S-T-T-T-S', 'S-T-T-S-T-T-T', 'T-T-T-S-T-T-S'],
                        correctIndex: 1,
                        explanation: 'Orice gamă majoră, în orice tonalitate, urmează T-T-S-T-T-T-S.',
                    },
                    {
                        question: 'De ce Sol major are nevoie de Fa♯ în loc de un Fa simplu?',
                        choices: [
                            'Nu are — Sol major nu are diezi',
                            'Formula cere un ton întreg de la Mi la a 7-a treaptă, pe care numai Fa♯ îl oferă',
                            'Fa♯ sună pur și simplu mai bine',
                            'Toate gamele majore în afară de Do major au toate notele cu diez',
                        ],
                        correctIndex: 1,
                        explanation: 'Urmând T-T-S-T-T-T-S de la Sol, ajungem exact pe Fa♯ pentru a 7-a treaptă — un Fa simplu ar fi doar un semiton față de Mi, rupând formula.',
                    },
                    {
                        question: 'Cum se numește treapta 1 a unei game majore?',
                        choices: ['Dominanta', 'Subdominanta', 'Tonica', 'Sensibila'],
                        correctIndex: 2,
                        explanation: 'Tonica este nota acasă după care se numesc gama și tonalitatea.',
                    },
                    {
                        question: 'Câte note distincte are o gamă majoră înainte de a se repeta?',
                        choices: ['5', '6', '7', '8'],
                        correctIndex: 2,
                        explanation: 'Șapte trepte distincte, cu a 8-a notă fiind tonica repetată o octavă mai sus.',
                    },
                ],
            },
            {
                id: 'relative-minor',
                title: 'Gama Minoră Naturală și Tonalitățile Relative',
                summary: 'Cum fiecare tonalitate majoră are un „geamăn" minor care îi împărtășește armura.',
                content: [
                    'Gama minoră naturală are propria formulă: T-S-T-T-S-T-T. Față de major, treptele a 3-a, a 6-a și a 7-a sunt fiecare cu un semiton mai joase, ceea ce conferă tonalităților minore caracterul lor mai întunecat.',
                    'Fiecare tonalitate majoră are o relativă minoră: pornind notele gamei majore de la treapta a 6-a în loc de treapta 1, obții gama minoră naturală cu un set identic de note — și prin urmare o armură identică. A 6-a treaptă a lui Do major este La, deci La minor este relativa minoră a lui Do major: aceleași șapte note (fără diezi/bemoli), tonică diferită.',
                    'Această relație explică de ce o piesă „în La minor" și una „în Do major" pot folosi exact aceeași armură pe portativ — diferă numai nota pe care muzica o tratează ca „acasă".',
                ],
                practice: { category: 'scales', difficulty: 'easy', label: 'Game · Ușor' },
                quiz: [
                    {
                        question: 'Față de o gamă majoră, care trepte sunt coborâte în gama minoră naturală?',
                        choices: ['A 2-a, a 4-a, a 6-a', 'A 3-a, a 6-a, a 7-a', 'A 3-a, a 5-a, a 7-a', 'A 2-a, a 3-a, a 5-a'],
                        correctIndex: 1,
                        explanation: 'Gama minoră naturală coboară treptele a 3-a, a 6-a și a 7-a față de gama majoră de pe aceeași tonică.',
                    },
                    {
                        question: 'Care este relativa minoră a lui Do major?',
                        choices: ['Fa minor', 'Sol minor', 'La minor', 'Mi minor'],
                        correctIndex: 2,
                        explanation: 'La este treapta a 6-a a gamei Do major, deci La minor este relativa minoră a lui Do major — aceleași note, aceeași armură.',
                    },
                    {
                        question: 'Cum găsești relativa minoră a unei game majore?',
                        choices: [
                            'Pornești aceleași note de la treapta a 6-a',
                            'Ridici fiecare notă cu un semiton',
                            'Pornești aceleași note de la treapta a 4-a',
                            'Cânți gama invers',
                        ],
                        correctIndex: 0,
                        explanation: 'Renumerotând treapta a 6-a a gamei majore ca noul „1" obții gama minoră naturală relativă.',
                    },
                    {
                        question: 'De ce Do major și La minor împărtășesc aceeași armură?',
                        choices: [
                            'De fapt nu o împărtășesc',
                            'Folosesc exact aceleași șapte note, pornind dintr-o tonică diferită',
                            'O coincidență fără motiv de bază',
                            'Deoarece La minor este mai puternic',
                        ],
                        correctIndex: 1,
                        explanation: 'O armură reflectă ce note sunt folosite, nu care este „acasă" — perechile major/minor relative folosesc note identice.',
                    },
                ],
            },
            {
                id: 'key-signatures',
                title: 'Armuri și Cercul Cvintelor',
                summary: 'Ordinea în care se adaugă diezii și bemolii, și cum cercul cvintelor organizează toate tonalitățile.',
                content: [
                    'Armurile nu adaugă diezi sau bemoli în ordine aleatorie. Diezii se adaugă mereu în această secvență: Fa♯, Do♯, Sol♯, Re♯, La♯, Mi♯, Si♯. Bemolii se adaugă în exact secvența inversă: Si♭, Mi♭, La♭, Re♭, Sol♭, Do♭, Fa♭.',
                    'Cercul cvintelor aranjează toate cele doisprezece tonalități majore într-un cerc unde fiecare pas în sensul acelor de ceasornic este o cvintă justă în sus și adaugă un diez, iar fiecare pas în sens invers este o cvintă justă în jos (sau o cvartă în sus) și adaugă un bemol. Do major se află în vârf fără diezi sau bemoli; Sol (un diez) este un pas în sensul acelor de ceasornic; Fa (un bemol) este un pas în sens invers.',
                    'Aceasta nu este doar teorie — pentru că fiecare nouă tonalitate cu diez/bemol este construită pe precedenta prin ridicarea sau coborârea exact a unei note, cercul cvintelor este și o hartă a cât de înrudite sunt orice două tonalități, motiv pentru care atât de multe progresii de acorduri se mișcă în jurul lui.',
                ],
                practice: { category: 'keysig', difficulty: 'easy', label: 'Armuri · Ușor' },
                quiz: [
                    {
                        question: 'În ce ordine se adaugă diezii la o armură?',
                        choices: [
                            'Fa♯, Do♯, Sol♯, Re♯, La♯, Mi♯, Si♯',
                            'Si♯, Mi♯, La♯, Re♯, Sol♯, Do♯, Fa♯',
                            'Do♯, Re♯, Mi♯, Fa♯, Sol♯, La♯, Si♯',
                            'Aleatoriu, în funcție de tonalitate',
                        ],
                        correctIndex: 0,
                        explanation: 'Diezii se acumulează mereu în ordinea fixă Fa♯-Do♯-Sol♯-Re♯-La♯-Mi♯-Si♯.',
                    },
                    {
                        question: 'Care este ordinea bemolilor?',
                        choices: [
                            'Aceeași ca a diezilor',
                            'Exact inversul ordinii diezilor: Si♭, Mi♭, La♭, Re♭, Sol♭, Do♭, Fa♭',
                            'Alfabetică: La♭, Si♭, Do♭...',
                            'Nu există o ordine fixă pentru bemoli',
                        ],
                        correctIndex: 1,
                        explanation: 'Bemolii se acumulează în ordinea-oglindă a diezilor.',
                    },
                    {
                        question: 'Deplasarea cu un pas în sensul acelor de ceasornic pe cercul cvintelor dintr-o tonalitate majoră dată face ce?',
                        choices: [
                            'Coboară o cvintă justă și elimină un diez',
                            'Urcă o cvintă justă și adaugă un diez (sau elimină un bemol)',
                            'Nu are legătură cu diezii sau bemolii',
                            'Schimbă tonalitatea la relativa sa minoară',
                        ],
                        correctIndex: 1,
                        explanation: 'Fiecare pas în sensul acelor de ceasornic este o cvintă justă mai sus și adaugă exact un diez la armură.',
                    },
                    {
                        question: 'Ce tonalitate se află direct opusă lui Do major pe cercul cvintelor, cu cei mai mulți diezi/bemoli?',
                        choices: ['Sol major', 'Fa♯ / Sol♭ major', 'Re major', 'Si♭ major'],
                        correctIndex: 1,
                        explanation: 'Fa♯ major (6 diezi) și gemenele sale enarmonice Sol♭ major (6 bemoli) se află la punctul cel mai îndepărtat de Do pe cerc.',
                    },
                ],
            },
            {
                id: 'modes',
                title: 'Moduri Dincolo de Major și Minor',
                summary: 'Dorian, Frigian, Lidian, Mixolidian și Locrian ca game majore/minore alterate.',
                content: [
                    'Un mod este ceea ce obții luând setul de note al unei game majore și tratând o altă treaptă ca „acasă." Există șapte moduri în total; le cunoști deja pe două sub alte denumiri — Ionian este pur și simplu gama majoră, iar Aeolian este gama minoră naturală.',
                    'Cel mai ușor mod de a înțelege celelalte este ca o gamă minoră sau majoră cu o treaptă alterată: Dorian este o gamă minoră cu a 6-a treaptă ridicată (majoră); Frigian este o gamă minoră cu a 2-a treaptă coborâtă; Lidian este o gamă majoră cu a 4-a treaptă ridicată; Mixolidian este o gamă majoră cu a 7-a treaptă coborâtă; Locrian este o gamă minoră cu atât a 2-a cât și a 5-a treaptă coborâtă.',
                    'Fiecare are un caracter distinct: Dorian sună minor dar mai luminos (frecvent în jazzul modal și muzica celtică/folk), Mixolidian sună major dar blues (frecvent peste acorduri de dominantă septimă), iar Lidian are o calitate visătoare, plutitoare datorată acelei a 4-a trepte ridicate.',
                ],
                practice: { category: 'scales', difficulty: 'hard', label: 'Game · Greu' },
                quiz: [
                    {
                        question: 'Care mod este identic cu gama minoră naturală?',
                        choices: ['Dorian', 'Aeolian', 'Mixolidian', 'Lidian'],
                        correctIndex: 1,
                        explanation: 'Aeolian este pur și simplu un alt nume pentru gama minoră naturală.',
                    },
                    {
                        question: 'Dorian poate fi descris ca:',
                        choices: [
                            'O gamă majoră cu a 7-a treaptă coborâtă',
                            'O gamă minoră cu a 6-a treaptă ridicată (majoră)',
                            'O gamă minoră cu a 2-a treaptă coborâtă',
                            'O gamă majoră cu a 4-a treaptă ridicată',
                        ],
                        correctIndex: 1,
                        explanation: 'Dorian ia gama minoră naturală și ridică a 6-a treaptă, conferindu-i o margine mai luminoasă decât minorul simplu.',
                    },
                    {
                        question: 'Care mod este o gamă majoră cu a 4-a treaptă ridicată?',
                        choices: ['Lidian', 'Mixolidian', 'Frigian', 'Locrian'],
                        correctIndex: 0,
                        explanation: 'Lidian ridică a 4-a treaptă a gamei majore, producând sunetul său visător, plutitor.',
                    },
                    {
                        question: 'Mixolidianul este frecvent folosit peste ce tip de acord?',
                        choices: ['Acorduri de septimă diminuată', 'Acorduri de dominantă septimă', 'Numai acorduri de septimă majoră', 'Nu are o utilizare acordică frecventă'],
                        correctIndex: 1,
                        explanation: 'A 7-a treaptă coborâtă a mixolidianului se potrivește cu a 7-a coborâtă dintr-un acord de dominantă septimă, făcând combinația naturală.',
                    },
                ],
            },
            {
                id: 'harmonic-melodic-minor',
                title: 'Minorul Armonic și Melodic',
                summary: 'De ce minorul natural este „corectat" pentru cadențe și melodii.',
                content: [
                    'Minorul natural are o problemă: a sa a 7-a treaptă se află la un ton întreg sub tonică, nu la un semiton, deci nu are sensibilă. În La minor natural (La-Si-Do-Re-Mi-Fa-Sol), triadă construită pe treapta a 5-a este Mi-Sol-Si — Mi minor — iar un acord v minor nu trage spre tonică aproape la fel de puternic cum o face un V major în o tonalitate majoră.',
                    'Minorul armonic rezolvă această problemă ridicând a 7-a treaptă cu un semiton: La-Si-Do-Re-Mi-Fa-Sol♯. Acum triada pe treapta a 5-a este Mi-Sol♯-Si, un V major, cu o adevărată sensibilă (Sol♯, la un semiton sub La) — oferind tonalităților minore aceeași cadență autentică puternică V-i pe care tonalitățile majore o primesc din V-I. Compromisul este melodic: intervalul dintre a 6-a (necoborâtă) și a 7-a (ridicată) (Fa la Sol♯) este un interval de secundă mărită, care conferă minorului armonic sunetul său distinctiv exotic, de coloratură orientală.',
                    'Minorul melodic netezește acel interval pentru melodii treptate ridicând atât a 6-a cât și a 7-a treaptă la urcare: La-Si-Do-Re-Mi-Fa♯-Sol♯-La, eliminând complet saltul incomod. Clasic, forma descendentă revine la minorul natural (a 6-a și a 7-a coborâte), deoarece atracția sensibilei contează mai ales la urcare spre tonică; jazzul modern folosește de obicei aceeași formă cu a 6-a și a 7-a ridicate în ambele direcții, numită uneori gama „jazz minor".',
                ],
                practice: { category: 'scales', difficulty: 'medium', label: 'Game · Mediu' },
                quiz: [
                    {
                        question: 'De ce minorul natural nu poate produce o cadență autentică puternică V-i ca tonalitățile majore?',
                        choices: [
                            'Minorul natural are prea mulți bemoli',
                            'A sa a 7-a treaptă se află la un ton întreg sub tonică, deci acordul construit acolo este minor (v), nu major (V)',
                            'Tonalitățile minore nu au voie să cadențeze',
                            'Minorul natural nu are deloc o a 5-a treaptă',
                        ],
                        correctIndex: 1,
                        explanation: 'Fără o sensibilă la un semiton sub tonică, acordul construit pe treapta a 5-a iese minor, lipsind atracția puternică pe care o oferă un V major.',
                    },
                    {
                        question: 'Ce schimbă minorul armonic față de minorul natural?',
                        choices: [
                            'Ridică a 7-a treaptă cu un semiton, creând o sensibilă',
                            'Coboară a 2-a treaptă',
                            'Ridică fiecare treaptă cu un semiton',
                            'Elimină a 3-a treaptă',
                        ],
                        correctIndex: 0,
                        explanation: 'Ridicând doar a 7-a treaptă, acordul v minor devine V major, restabilind o adevărată sensibilă și o cadență puternică.',
                    },
                    {
                        question: 'Ce efect melodic secundar creează a 7-a treaptă ridicată a minorului armonic?',
                        choices: [
                            'O gamă mai fluentă, cu sunet mai major în ansamblu',
                            'Un interval de secundă mărită între a 6-a (necoborâtă) și a 7-a (ridicată) treaptă',
                            'Niciun efect audibil',
                            'Elimină sensibila tocmai creată',
                        ],
                        correctIndex: 1,
                        explanation: 'Cu numai a 7-a ridicată, distanța de la treapta a 6-a la a 7-a se extinde la trei semitonuri — o secundă mărită, conferind minorului armonic caracterul său exotic.',
                    },
                    {
                        question: 'Cum evită gama de minor melodic (clasic, la urcare) acel interval de secundă mărită?',
                        choices: [
                            'Ridică atât a 6-a cât și a 7-a treaptă, închizând intervalul',
                            'Coboară și mai mult a 7-a treaptă',
                            'Este identică cu minorul armonic',
                            'Elimină complet a 6-a treaptă',
                        ],
                        correctIndex: 0,
                        explanation: 'Ridicând și a 6-a treaptă, se restabilește un interval normal de ton întreg între treptele a 6-a și a 7-a, fluidizând linia la urcare spre tonică.',
                    },
                ],
            },
        ],
    },
    {
        id: 'chords-harmony',
        title: 'Acorduri și Armonie',
        description: 'Stivuiește intervale în triade și acorduri de septimă, apoi vezi cum acordurile sunt organizate în cadrul unei tonalități.',
        lessons: [
            {
                id: 'triads',
                title: 'Triade: Major, Minor, Diminuat, Mărit',
                summary: 'Stivuirea a două terțe pentru a construi cele patru calități de triade de bază.',
                content: [
                    'O triadă este construită stivuind două terțe deasupra unei fundamentale. Calitatea celor două terțe stivuite determină calitatea acordului: major (terță mare + terță mică), minor (terță mică + terță mare), diminuat (terță mică + terță mică) și mărit (terță mare + terță mare).',
                    'În semitonuri față de fundamentală: major este 0-4-7, minor este 0-3-7, diminuat este 0-3-6 și mărit este 0-4-8. Triadele major și minor împărtășesc același interval exterior (o cvintă justă, 7 semitonuri), dar diferă prin poziția notei de mijloc; diminuatul strânge acea cvintă până la un triton, iar măritul o extinde.',
                    'Triadele majore sună luminos și rezolvat, cele minore sună mai întunecat, cele diminuate sună tensionat și instabil (deseori folosite pentru a conduce undeva), iar cele mărite sună simetric și ambiguu, fără atracție puternică în nicio direcție.',
                ],
                practice: { category: 'chords', difficulty: 'easy', label: 'Acorduri · Ușor' },
                quiz: [
                    {
                        question: 'O triadă majoră este construită din ce două intervale stivuite?',
                        choices: [
                            'Terță mică apoi terță mare',
                            'Terță mare apoi terță mică',
                            'Două terțe mari',
                            'Două terțe mici',
                        ],
                        correctIndex: 1,
                        explanation: 'Triadă majoră = fundamentală, terță mare sus, apoi terță mică sus de acolo (0-4-7 în semitonuri).',
                    },
                    {
                        question: 'Ce tipar de semitonuri (față de fundamentală) are o triadă diminuată?',
                        choices: ['0-4-7', '0-3-7', '0-3-6', '0-4-8'],
                        correctIndex: 2,
                        explanation: 'Diminuatul stivuiește două terțe mici: 0-3-6, terminând cu un triton deasupra fundamentalei.',
                    },
                    {
                        question: 'Ce triadă este construită din două terțe mari stivuite?',
                        choices: ['Major', 'Minor', 'Diminuat', 'Mărit'],
                        correctIndex: 3,
                        explanation: 'Triadele mărite stivuiesc o terță mare deasupra alteia (0-4-8), făcându-le perfect simetrice.',
                    },
                    {
                        question: 'Triadele major și minor împărtășesc ce interval între fundamentală și nota de sus?',
                        choices: ['Un triton', 'O cvintă justă', 'O sextă mare', 'O cvintă mărită'],
                        correctIndex: 1,
                        explanation: 'Atât major (0-4-7) cât și minor (0-3-7) cuprind o cvintă justă (7 semitonuri) de la fundamentală la nota de sus — diferă numai nota de mijloc.',
                    },
                ],
            },
            {
                id: 'seventh-chords',
                title: 'Acorduri de Septimă',
                summary: 'Adăugarea unei a 4-a note deasupra triadei pentru o armonie mai bogată, mai jazz.',
                content: [
                    'Un acord de septimă este o triadă cu încă o terță stivuită deasupra, adăugând a 7-a treaptă a acordului. Cele cinci tipuri cele mai frecvente: septimă majoră (triadă majoră + septimă majoră, 0-4-7-11), septimă minoră (triadă minoră + septimă minoră, 0-3-7-10), dominantă septimă (triadă majoră + septimă minoră, 0-4-7-10), minor 7♭5 / semidiminuat (triadă diminuată + septimă minoră, 0-3-6-10) și septimă diminuată (triadă diminuată + septimă diminuată, 0-3-6-9).',
                    'Dominanta septimă este deosebit de importantă: acea combinație de triadă majoră plus septimă minoră creează o atracție puternică înapoi spre acordul tonic, motiv pentru care este coloana vertebrală a bluesului și „V7" în cadențele clasice.',
                    'Acordurile de septimă majoră sună luxuriant și visător (frecvente în baladele jazz și bossa nova); acordurile de septimă minoră sună lin și cald; acordurile de septimă diminuată sunt maxim tensionate și, deoarece sunt construite din terțe mici stivuite tot drumul, perfect simetrice.',
                ],
                practice: { category: 'chords', difficulty: 'hard', label: 'Acorduri · Greu' },
                quiz: [
                    {
                        question: 'Ce diferențiază un acord de dominantă septimă de un acord de septimă majoră?',
                        choices: [
                            'Dominanta septimă are o septimă minoră deasupra unei triade majore; septimă majoră are o septimă majoră',
                            'Sunt același acord cu denumiri diferite',
                            'Dominanta septimă nu are terță',
                            'Septimă majoră este mereu minoră ca și calitate',
                        ],
                        correctIndex: 0,
                        explanation: 'Ambele pornesc de la o triadă majoră, dar dominanta septimă adaugă o septimă minoră (0-4-7-10) în timp ce septimă majoră adaugă o septimă majoră (0-4-7-11).',
                    },
                    {
                        question: 'De ce acordul de dominantă septimă este atât de central în cadențe?',
                        choices: [
                            'Nu are nicio tendință de a rezolva undeva',
                            'Combinația de terță mare și septimă minoră creează o atracție puternică înapoi spre tonică',
                            'Funcționează numai în tonalități minore',
                            'Este cel mai simplu acord posibil',
                        ],
                        correctIndex: 1,
                        explanation: 'Acea tensiune specifică terță-mare-plus-septimă-minoră este ceea ce conferă acordurilor V7 senzația puternică de „nevoie de rezolvare".',
                    },
                    {
                        question: 'Un acord semidiminuat (minor 7♭5) este construit din ce triadă plus ce septimă?',
                        choices: [
                            'Triadă majoră + septimă majoră',
                            'Triadă minoră + septimă minoră',
                            'Triadă diminuată + septimă minoră',
                            'Triadă mărită + septimă majoră',
                        ],
                        correctIndex: 2,
                        explanation: 'Semidiminuat = triadă diminuată (0-3-6) plus o septimă minoră deasupra (0-3-6-10).',
                    },
                    {
                        question: 'De ce acordul de septimă diminuată este descris ca „perfect simetric"?',
                        choices: [
                            'Are numai două note',
                            'Este construit din terțe mici stivuite tot drumul (0-3-6-9)',
                            'Conține o cvintă justă și nimic altceva',
                            'Este identic cu o triadă majoră',
                        ],
                        correctIndex: 1,
                        explanation: 'Fiecare interval dintre note adiacente dintr-un acord de septimă diminuată este aceeași terță mică, făcându-l simetric.',
                    },
                ],
            },
            {
                id: 'chord-inversions',
                title: 'Răsturnări de Acorduri și Acorduri Slash',
                summary: 'Aceleași sunete ale acordului, altă notă la bas.',
                content: [
                    'Un acord este în poziție fundamentală atunci când fundamentala sa este nota cea mai de jos. Punerea oricărei alte note ale acordului la bază — fără a schimba ce note conțin acordul — se numește răsturnare. O triadă Do major (Do-Mi-Sol) în poziție fundamentală are Do la bază; pune Mi la bază (Mi-Sol-Do) și este în prima răsturnare; pune Sol la bază (Sol-Do-Mi) și este în a doua răsturnare. Este tot un acord Do major — numai nota de bas s-a mișcat.',
                    'Acordurile de septimă au o răsturnare în plus disponibilă, deoarece au o notă în plus de pus la bază: a treia răsturnare pune a 7-a a acordului la bază. Pentru un acord Sol7 (Sol-Si-Re-Fa), aceasta dă poziție fundamentală (bas Sol), prima răsturnare (bas Si), a doua răsturnare (bas Re) și a treia răsturnare (bas Fa).',
                    'Răsturnările sunt de obicei notate cu notație slash: „Do/Mi" înseamnă un acord Do major cu Mi la bas. Aranjatorii și basisții apelează constant la răsturnări pentru a construi linii de bas mai fluide, mai treptate — de exemplu, Do, Sol/Si, La minor mișcă basul Do-Si-La în pași mici, în loc să sară o cvintă în jos de la Do la Sol cum ar face un acord Sol în poziție fundamentală.',
                ],
                practice: { category: 'chords', difficulty: 'medium', label: 'Acorduri · Mediu' },
                quiz: [
                    {
                        question: 'Ce definește o răsturnare a unui acord?',
                        choices: [
                            'O notă a acordului alta decât fundamentala este nota cea mai de jos, în timp ce notele acordului rămân aceleași',
                            'Una sau mai multe note sunt adăugate acordului',
                            'Calitatea acordului se schimbă de la major la minor',
                            'Acordul este cântat într-o altă tonalitate',
                        ],
                        correctIndex: 0,
                        explanation: 'Răsturnarea schimbă numai care notă a acordului se află la bas — acordul este în continuare construit din aceleași note.',
                    },
                    {
                        question: 'Într-o triadă Do major (Do-Mi-Sol), ce notă este la bas în prima răsturnare?',
                        choices: ['Do', 'Mi', 'Sol', 'Si'],
                        correctIndex: 1,
                        explanation: 'Prima răsturnare pune terța (Mi) la bas; poziția fundamentală are Do, a doua răsturnare are Sol (cvinta).',
                    },
                    {
                        question: 'De ce acordurile de septimă au o a treia răsturnare, pe când triadele merg doar până la a doua răsturnare?',
                        choices: [
                            'Triadele au trei note (fundamentală, terță, cvintă) și deci doi bași posibili non-fundamentali; nota suplimentară a unui acord de septimă (septima) creează o a treia opțiune',
                            'Acordurile de septimă nu sunt de fapt răsturnabile',
                            'Triadele pot fi răsturnate de patru ori și ele',
                            'Nu există nicio diferență reală între ele',
                        ],
                        correctIndex: 0,
                        explanation: 'Fiecare notă a acordului în afară de fundamentală poate deveni nota de bas — un acord de septimă cu 4 note are cu una mai mult dintre acestea decât o triadă cu 3 note.',
                    },
                    {
                        question: 'Ce înseamnă simbolul de acord „Do/Mi"?',
                        choices: [
                            'Un acord Do major cu Mi la bas',
                            'Cântă Do, apoi cântă Mi',
                            'Un acord Do cu Mi eliminat',
                            'O greșeală de tipar pentru „Do7"',
                        ],
                        correctIndex: 0,
                        explanation: 'Notația slash se citește ca „[acord]/[notă de bas]" — Do/Mi este un acord Do major, prima răsturnare, cu Mi la bază.',
                    },
                ],
            },
            {
                id: 'diatonic-harmony',
                title: 'Armonie Diatonică și Cifre Romane',
                summary: 'Construirea unui acord pe fiecare treaptă a unei game majore.',
                content: [
                    'Dacă construiești o triadă pe fiecare treaptă a unei game majore, folosind numai notele din acea gamă, obții un tipar repetabil, predictibil de calități: I (major), ii (minor), iii (minor), IV (major), V (major), vi (minor), vii° (diminuat). Acesta este adevărat în fiecare tonalitate majoră — numai numele reale ale notelor se schimbă.',
                    'Cifrele romane exprimă aceasta direct: majuscule pentru acorduri majore, minuscule pentru minore și un simbol de grad (°) pentru diminuat. Scrierea unei progresii în cifre romane (ca I-IV-V) descrie forma ei independentă de tonalitate, motiv pentru care aceeași progresie numerică poate fi cântată în orice tonalitate fără a-i schimba funcția.',
                    'Acest tipar explică de ce anumite acorduri se simt mereu similar ca rol: acordul V este mereu major și mereu vrea să rezolve, acordul vii° este mereu diminuat și mereu sună instabil, indiferent de tonalitate.',
                ],
                practice: { category: 'progressions', difficulty: 'easy', label: 'Progresii de Acorduri · Ușor' },
                quiz: [
                    {
                        question: 'Ce calitate are acordul iii într-o tonalitate majoră?',
                        choices: ['Major', 'Minor', 'Diminuat', 'Mărit'],
                        correctIndex: 1,
                        explanation: 'Tiparul de triade diatonice în major este I-ii-iii-IV-V-vi-vii°, unde iii este minor.',
                    },
                    {
                        question: 'Ce treaptă a gamei produce întotdeauna o triadă diminuată într-o tonalitate majoră?',
                        choices: ['A 2-a (ii)', 'A 5-a (V)', 'A 7-a (vii°)', 'A 1-a (I)'],
                        correctIndex: 2,
                        explanation: 'Triada construită pe treapta a 7-a a unei game majore este mereu diminuată — de aceea vii°.',
                    },
                    {
                        question: 'De ce se folosesc cifrele romane în loc de denumirile de note ale acordurilor?',
                        choices: [
                            'Descriu forma unei progresii independent de tonalitate',
                            'Funcționează numai în Do major',
                            'Înlocuiesc necesitatea de a cunoaște calitățile acordurilor',
                            'Sunt pur și simplu notație decorativă',
                        ],
                        correctIndex: 0,
                        explanation: 'I-IV-V înseamnă același tipar funcțional indiferent dacă ești în Do, Sol sau orice altă tonalitate — numai denumirile notelor se schimbă.',
                    },
                    {
                        question: 'În sistemul cifrelor romane, ce indică o cifră minusculă?',
                        choices: ['Un acord diminuat', 'Un acord major', 'Un acord minor', 'Un acord de septimă'],
                        correctIndex: 2,
                        explanation: 'Cifrele minuscule (ii, iii, vi) indică triade minore; cele majuscule (I, IV, V) indică majore.',
                    },
                ],
            },
            {
                id: 'functional-harmony',
                title: 'Armonie Funcțională: Tonică, Subdominantă, Dominantă',
                summary: 'De ce progresiile par să meargă undeva.',
                content: [
                    'Acordurile diatonice se grupează în trei funcții. Tonica (I, vi) se simte ca „acasă" — stabilă, rezolvată, un loc de odihnă. Subdominanta (ii, IV) se simte ca o mișcare departe de acasă, construind anticipare. Dominanta (V, vii°) se simte ca tensiune maximă, cerând revenirea la tonică.',
                    'O cadență este o mișcare de acorduri care încheie o frază muzicală. Cea mai puternică este cadența autentică, V-I (sau V7-I) — dominanta rezolvând direct spre tonică. Cadența plagală, IV-I, este mai blândă și este uneori numită „cadența Amin" datorită folosirii ei în imnuri.',
                    'Nu orice frază rezolvă complet acasă. O semicadență se termină pe V în loc de I — sună „deschis", ca o întrebare mai degrabă decât un final complet, motiv pentru care este atât de frecventă la finalul unei fraze care așteaptă o altă frază care să îi răspundă. O cadență înșelătoare creează aceeași așteptare dar rezolvă V spre vi în loc de I — urechea aude atracția dominantei spre „acasă" și este redirecționată în ultimul moment, un mod clasic de a extinde o frază sau de a adăuga o surpriză înainte de finalul real.',
                    'Cunoașterea acestor funcții îți permite să prezici și să scrii progresii cu scop: cele mai multe progresii sunt un drum prin subdominantă, spre dominantă și înapoi la tonică — T-S-D-T este scheletul de bază sub o cantitate enormă de muzică.',
                ],
                practice: { category: 'progressions', difficulty: 'medium', label: 'Progresii de Acorduri · Mediu' },
                quiz: [
                    {
                        question: 'Ce acorduri au funcție „tonică" într-o tonalitate majoră?',
                        choices: ['I și vi', 'ii și IV', 'V și vii°', 'iii și vi'],
                        correctIndex: 0,
                        explanation: 'I (tonica însăși) și vi (cea mai apropiată rudă a ei) poartă ambele funcția de tonică, „acasă".',
                    },
                    {
                        question: 'Ce este o cadență autentică?',
                        choices: ['IV la I', 'V (sau V7) la I', 'I la V', 'ii la vi'],
                        correctIndex: 1,
                        explanation: 'V-I (sau V7-I) este cadența cea mai puternică, mai conclusivă — dominanta rezolvând la tonică.',
                    },
                    {
                        question: 'Cadența plagală (IV-I) este uneori numită:',
                        choices: ['Cadența de blues', 'Cadența Amin', 'Cadența înșelătoare', 'Semicadența'],
                        correctIndex: 1,
                        explanation: 'IV-I este numită „cadența Amin" din cauza utilizării ei frecvente la finalul imnurilor.',
                    },
                    {
                        question: 'Care este scheletul funcțional de bază din spatele celor mai frecvente progresii?',
                        choices: ['Numai dominantă', 'Tonică - Subdominantă - Dominantă - Tonică', 'Numai subdominantă', 'Ordine aleatorie de acorduri'],
                        correctIndex: 1,
                        explanation: 'T-S-D-T (pleacă acasă, construiește tensiune, rezolvă înapoi) stă la baza unei imense cantități de muzică populară și clasică.',
                    },
                    {
                        question: 'Ce diferențiază o semicadență de o cadență înșelătoare?',
                        choices: [
                            'O semicadență se termină pe V (sună „deschis"); o cadență înșelătoare rezolvă V spre vi în loc de I așteptat',
                            'Sunt două denumiri pentru aceeași cadență',
                            'O semicadență se termină mereu pe I',
                            'O cadență înșelătoare apare numai în tonalități minore',
                        ],
                        correctIndex: 0,
                        explanation: 'Semicadență = fraza se oprește pe V însuși. Cadență înșelătoare = dominanta rezolvă, dar spre vi în loc de I așteptat, redirecționând urechea în ultimul moment.',
                    },
                ],
            },
        ],
    },
    {
        id: 'progressions',
        title: 'Progresii de Acorduri',
        description: 'Vede armonia funcțională în acțiune prin progresiile care apar peste tot.',
        lessons: [
            {
                id: 'pop-progressions',
                title: 'Progresii Frecvente Pop și Rock',
                summary: 'I-IV-V, I-V-vi-IV și „progresia anilor \'50".',
                content: [
                    'I-IV-V-I este una dintre progresiile fundamentale: tonică, subdominantă, dominantă, înapoi la tonică. Este coloana vertebrală armonică a bluesului și a unei mari părți din muzica rock și folk.',
                    'I-V-vi-IV este progresia numită „cele patru acorduri" — instantaneu recognoscibilă deoarece alimentează un număr enorm de hituri pop de-a lungul deceniilor. Varianta sa apropiată, I-vi-IV-V, este numită „progresia anilor \'50" pentru utilizarea ei în doo-wop și primele piese rock \'n\' roll.',
                    'O variantă cu simț minor, vi-IV-I-V, rotește pur și simplu aceleași patru acorduri pentru a începe de la relativa minoră în loc de tonică — același conținut armonic, punct de plecare emoțional diferit.',
                ],
                practice: { category: 'progressions', difficulty: 'easy', label: 'Progresii de Acorduri · Ușor' },
                quiz: [
                    {
                        question: 'Ce funcții parcurge progresia I-IV-V-I?',
                        choices: [
                            'Tonică, dominantă, subdominantă, tonică',
                            'Tonică, subdominantă, dominantă, tonică',
                            'Numai subdominantă',
                            'Dominantă, tonică, subdominantă, dominantă',
                        ],
                        correctIndex: 1,
                        explanation: 'I-IV-V-I se mișcă tonică -> subdominantă -> dominantă -> înapoi la tonică, cea mai simplă călătorie armonică.',
                    },
                    {
                        question: 'Progresia „cele patru acorduri" celebră pentru apariția ei în nenumărate piese pop este:',
                        choices: ['I-vi-IV-V', 'ii-V-I', 'I-V-vi-IV', 'I-IV-vii°-iii'],
                        correctIndex: 2,
                        explanation: 'I-V-vi-IV este progresia frecvent numită „cele patru acorduri" din cauza cât de des revine în muzica pop.',
                    },
                    {
                        question: 'Care este „progresia anilor \'50"?',
                        choices: ['I-vi-IV-V', 'vi-ii-V-I', 'I-iii-IV-V', 'I-IV-V-I'],
                        correctIndex: 0,
                        explanation: 'I-vi-IV-V este numită progresia anilor \'50 pentru utilizarea sa intensă în doo-wop și primele piese rock \'n\' roll.',
                    },
                    {
                        question: 'Cum se raportează vi-IV-I-V la I-V-vi-IV?',
                        choices: [
                            'Este o progresie complet diferită',
                            'Sunt aceleași patru acorduri, rotite pentru a începe de la relativa minoră',
                            'Folosește acorduri complet diferite',
                            'Funcționează numai în tonalități minore',
                        ],
                        correctIndex: 1,
                        explanation: 'Rotirea acordului cu care începe ciclul schimbă punctul de plecare emoțional fără a schimba armonia de fond.',
                    },
                ],
            },
            {
                id: 'jazz-ii-v-i',
                title: 'Cadența ii-V-I din Jazz',
                summary: 'Coloana vertebrală a armoniei jazz — și progresia completă a cercului.',
                content: [
                    'Progresia ii-V-I este cea mai frecventă cadență din jazz: un acord subdominant (ii), mișcând spre un acord dominant (V), rezolvând la tonică (I). Fiecare pas crește tensiunea până la rezolvarea finală.',
                    'Piesele jazz reale înlănțuiesc deseori mai multe perechi ii-V înainte de rezolvarea finală sau inserează acorduri diatonice suplimentare pe parcurs — de exemplu, vi-ii-V-I adaugă o introducere cu savoare minoră înainte de cadență.',
                    'Luată la extrem logic, obții progresia completă a cercului cvintelor: I-IV-vii°-iii-vi-ii-V-I, vizitând fiecare acord diatonic pe drumul înapoi acasă. Șase din cele șapte mișcări sunt adevărate cvinte descendente — singura excepție este IV la vii° (Fa la Si în Do major), care este un triton, nu o cvintă, deoarece gama majoră diatonică conține doar șase note la rând de cvinte juste perfecte (Fa-Do-Sol-Re-La-Mi-Si). Acel unic interval „ciudat" este înglobat în fiecare gamă majoră.',
                ],
                practice: { category: 'progressions', difficulty: 'hard', label: 'Progresii de Acorduri · Greu' },
                quiz: [
                    {
                        question: 'Ce funcții alcătuiesc cadența ii-V-I?',
                        choices: [
                            'Tonică, dominantă, subdominantă',
                            'Subdominantă, dominantă, tonică',
                            'Dominantă, tonică, subdominantă',
                            'Tonică, subdominantă, subdominantă',
                        ],
                        correctIndex: 1,
                        explanation: 'ii (subdominantă) -> V (dominantă) -> I (tonică) este forma clasică a cadențelor jazz.',
                    },
                    {
                        question: 'Ce adaugă vi-ii-V-I față de un ii-V-I simplu?',
                        choices: [
                            'Nimic, sunt identice',
                            'O introducere cu savoare minoră (vi) înainte de cadența jazz',
                            'Un acord dominant suplimentar',
                            'O schimbare de tonalitate',
                        ],
                        correctIndex: 1,
                        explanation: 'Pornind de la vi adaugă o introducere cu nuanță minoră înainte de a se stabili în rezolvarea familiară ii-V-I.',
                    },
                    {
                        question: 'Progresia completă a cercului cvintelor I-IV-vii°-iii-vi-ii-V-I se mișcă prin acorduri prin:',
                        choices: [
                            'Cvinte ascendente',
                            'Cvinte descendente (echivalent, cvarte ascendente)',
                            'Trepte ale gamei aleatorii',
                            'Numai semitonuri cromatice',
                        ],
                        correctIndex: 1,
                        explanation: 'Șase din cele șapte mișcări sunt o cvintă mai jos (sau o cvartă mai sus) față de acordul precedent. Singura excepție este IV la vii° (un triton, nu o cvintă) — singura relație non-cvintă-justă a gamei.',
                    },
                    {
                        question: 'De ce este ii-V-I considerat coloana vertebrală a armoniei jazz?',
                        choices: [
                            'Nu rezolvă niciodată',
                            'Apare rareori în piesele jazz reale',
                            'Construiește tensiune prin funcțiile subdominantă și dominantă înainte de o rezolvare satisfăcătoare și este reutilizat constant',
                            'Folosește numai acorduri majore',
                        ],
                        correctIndex: 2,
                        explanation: 'Forma sa clară de tensiune-și-eliberare îl face infinit reutilizabil și recognoscibil, motiv pentru care standardele jazz se bazează atât de mult pe el.',
                    },
                ],
            },
        ],
    },
    {
        id: 'rhythm-time',
        title: 'Ritm și Timp',
        description: 'Metru, durate de note și subdiviziunile care conferă muzicii groove-ul.',
        lessons: [
            {
                id: 'time-signatures',
                title: 'Timpi, Metru și Indicații de Timp',
                summary: 'Ce înseamnă de fapt cele două numere dintr-o indicație de timp.',
                content: [
                    'O indicație de timp are două numere. Cel de sus spune câți timpi sunt în fiecare măsură. Cel de jos spune ce valoare de notă contează ca un timp — un 4 înseamnă că pătrimea primește timpul, un 8 înseamnă că optimea o face.',
                    '4/4 (patru timpi de pătrime pe măsură) este de departe cel mai frecvent metru în muzica populară. 3/4 (trei timpi de pătrime) dă o simțire de vals. Acestea sunt metru „simple", unde fiecare timp se divide natural în două.',
                    '6/8 arată ca ar trebui să însemne „șase timpi de optime", dar aproape mereu se simte ca doi timpi mari, fiecare alcătuit din trei optimi — un metru „compus". Acea grupare de trei-înăuntrul-unui-timp este ceea ce dă lui 6/8 senzația sa curgătoare față de 3/4 sau 2/4.',
                ],
                practice: { category: 'rhythm', difficulty: 'easy', label: 'Ritm · Ușor' },
                quiz: [
                    {
                        question: 'Într-o indicație de timp, ce îți spune numărul de sus?',
                        choices: [
                            'Ce valoare de notă primește un timp',
                            'Câți timpi sunt în fiecare măsură',
                            'Tempo-ul în bătăi pe minut',
                            'Armura',
                        ],
                        correctIndex: 1,
                        explanation: 'Numărul de sus este numărul de timpi pe măsură; cel de jos spune ce valoare de notă este „un timp".',
                    },
                    {
                        question: 'În 4/4, ce valoare de notă primește un timp?',
                        choices: ['Notă de jumătate', 'Pătrime', 'Optime', 'Întreagă'],
                        correctIndex: 1,
                        explanation: 'Cifra „4" de jos înseamnă că pătrimea este unitatea de timp.',
                    },
                    {
                        question: 'Cum se simte de obicei 6/8, în ciuda numelui ce sugerează șase timpi?',
                        choices: [
                            'Ca șase timpi egali separați',
                            'Ca doi timpi mari, fiecare alcătuit din trei optimi',
                            'Ca trei timpi mari de câte două optimi',
                            'Nu se folosește niciodată în practică',
                        ],
                        correctIndex: 1,
                        explanation: '6/8 este un metru compus, simțit de obicei în două grupe de câte trei optimi, conferindu-i o senzație distinctă, curgătoare.',
                    },
                    {
                        question: 'Ce simțire produce de obicei 3/4?',
                        choices: ['O simțire rock pulsantă', 'O simțire de vals', 'O simțire compusă, curgătoare', 'Fără puls discernibil'],
                        correctIndex: 1,
                        explanation: 'Trei timpi de pătrime pe măsură este metrul clasic de vals.',
                    },
                ],
            },
            {
                id: 'note-durations',
                title: 'Durate de Note și Subdiviziune',
                summary: 'Cum se raportează întregile, jumătățile, pătrimile, optimile și șaisprezecimile — și ce face un punct.',
                content: [
                    'Duratele de note formează un lanț strict de înjumătățire: o întreagă egalează două jumătăți, o jumătate egalează două pătrimi, o pătrime egalează două optimi, iar o optime egalează două șaisprezecimi. Fiecare pas în jos împarte exact la jumătate durata precedentă.',
                    'Un punct plasat după o notă îi adaugă jumătate din propria sa valoare. O pătrime cu punct egalează o pătrime plus o optime (1,5 pătrimi) — de aceea ritmurile cu punct au o simțire „lung-scurt" în loc să fie împărțite uniform.',
                    'Subdiviziunea înseamnă pur și simplu numărarea pieselor mai mici din interiorul unui timp („1-și, 2-și" pentru optimi, „1-e-și-a" pentru șaisprezecimi). Interiorizarea subdiviziunilor este ceea ce permite unui interpret să cânte ritmuri cu acuratețe, nu doar aproximativ.',
                ],
                practice: { category: 'rhythm', difficulty: 'medium', label: 'Ritm · Mediu' },
                quiz: [
                    {
                        question: 'Câte optimi egalează o pătrime?',
                        choices: ['1', '2', '4', '3'],
                        correctIndex: 1,
                        explanation: 'Fiecare pas în jos pe lanțul de durate înjumătățește valoarea precedentă: o pătrime = două optimi.',
                    },
                    {
                        question: 'Ce face un punct după o notă cu durata sa?',
                        choices: [
                            'O dublează',
                            'Adaugă jumătate din propria valoare a notei la ea însăși',
                            'O înjumătățește',
                            'Nu are niciun efect',
                        ],
                        correctIndex: 1,
                        explanation: 'Un punct adaugă 50% din valoarea de bază a notei — o jumătate cu punct = o jumătate plus o pătrime.',
                    },
                    {
                        question: 'O pătrime cu punct este egală ca lungime cu:',
                        choices: [
                            'O pătrime plus o optime',
                            'Două pătrimi',
                            'O jumătate',
                            'O optime',
                        ],
                        correctIndex: 0,
                        explanation: 'Pătrime cu punct = pătrime (1 timp) + jumătate dintr-o pătrime (o optime, 0,5 timpi) = 1,5 timpi total.',
                    },
                    {
                        question: 'De ce este utilă subdivizarea timpilor (ex. numărând „1-și-2-și")?',
                        choices: [
                            'Nu are niciun beneficiu practic',
                            'Permite unui interpret să plaseze ritmurile cu acuratețe în loc de aproximativ',
                            'Contează numai pentru cititul la prima vedere, nu pentru cântat',
                            'Se folosește numai în jazz',
                        ],
                        correctIndex: 1,
                        explanation: 'Subdiviziunea interiorizată îți oferă o grilă internă constantă pe care să plasezi notele cu precizie.',
                    },
                ],
            },
            {
                id: 'syncopation',
                title: 'Sincopa și Pauzele',
                summary: 'Cântatul împotriva timpului așteptat și de ce tăcerea tot ocupă timp.',
                content: [
                    'Sincopa este accentul plasat acolo unde nu îl aștepți — pe un contratimp sau pe o parte slabă a timpului, în loc de arcada puternică, așteptată. Este o sursă majoră de „groove" în funk, jazz, reggae și cele mai multe secțiuni ritmice pop.',
                    'O pauză nu este o absență a ritmului — este o tăcere în formă de notă care ocupă exact atâta timp cât valoarea de notă pe care o reprezintă. O pauză de pătrime ocupă un timp de tăcere în 4/4 la fel de definitiv ca o pătrime ocupă un timp de sunet.',
                    'Combinarea notelor scurte, pauzelor și accentelor de contratimp este ceea ce separă un ritm plat, mecanic-sonor de unul care se simte viu. Ascultarea locului unde cad tăcerile și accentele este la fel de importantă ca ascultarea notelor înseși.',
                ],
                practice: { category: 'rhythm', difficulty: 'hard', label: 'Ritm · Greu' },
                quiz: [
                    {
                        question: 'Ce este sincopa?',
                        choices: [
                            'Cântatul fiecărei note pe arcadă',
                            'Accentul plasat pe un contratimp sau parte neașteptată a timpului',
                            'Un tip de armură',
                            'Un mod de a nota pauzele',
                        ],
                        correctIndex: 1,
                        explanation: 'Sincopa accentuează deliberat timpii slabi sau contratimpii mai degrabă decât timpii puternici așteptați.',
                    },
                    {
                        question: 'Cât timp ocupă o pauză de pătrime în 4/4?',
                        choices: [
                            'Deloc',
                            'Exact atât cât o pătrime (un timp)',
                            'Jumătate de timp',
                            'Variază în funcție de tempo, nu de valoarea duratei',
                        ],
                        correctIndex: 1,
                        explanation: 'O pauză ocupă exact aceeași cantitate de timp ca valoarea de notă echivalentă — tăcerea este tot ritm măsurat.',
                    },
                    {
                        question: 'Ce genuri sunt cunoscute în special pentru sincopa intensă?',
                        choices: ['Funk, jazz și reggae', 'Niciunul — sincopa este rară în muzica populară', 'Numai valsurile clasice', 'Numai muzica solo de pian'],
                        correctIndex: 0,
                        explanation: 'Secțiunile ritmice funk, jazz și reggae se bazează mult pe accentul de contratimp pentru groove-ul lor caracteristic.',
                    },
                    {
                        question: 'Ce separă în principal un ritm „plat" mecanic de unul „cu groove"?',
                        choices: [
                            'A cânta mai tare în general',
                            'Folosirea gândită a pauzelor, notelor scurte și accentelor de contratimp',
                            'Folosirea numai a notelor întregi',
                            'Evitarea completă a sincopei',
                        ],
                        correctIndex: 1,
                        explanation: 'Plasarea deliberată a tăcerilor și accentelor împotriva timpului este ceea ce creează senzația de groove.',
                    },
                ],
            },
        ],
    },
    {
        id: 'reading-music',
        title: 'Cititul Muzicii',
        description: 'Conectează portativul la sunete reale și transportă acea abilitate de numire a notelor pe grifă.',
        lessons: [
            {
                id: 'staff-clefs',
                title: 'Portativul, Cheile și Liniile Suplimentare',
                summary: 'Cinci linii, patru spații și mnemotehnicele care le denumesc.',
                content: [
                    'Un portativ muzical are cinci linii și patru spații, fiecare reprezentând un sunet specific. Ce sunet depinde de cheia plasată la început — cheia de sol (folosită pentru voci/instrumente mai înalte) și cheia de fa (folosită pentru cele mai joase) atribuie note complet diferite acelorași cinci linii.',
                    'În cheia de sol, liniile de jos în sus sunt Mi-Sol-Si-Re-Fa (mnemotehnică: „Mi-Sol-Si-Re-Fa" sau „Every Good Boy Does Fine"), iar spațiile formează Fa-La-Do-Mi. În cheia de fa, liniile sunt Sol-Si-Re-Fa-La, iar spațiile La-Do-Mi-Sol.',
                    'Notele care depășesc sus sau jos portativul folosesc linii suplimentare — linii scurte extra trasate doar pentru nota respectivă. Do din mijloc este exemplul clasic: se află pe o linie suplimentară sub portativul în cheia de sol și pe o linie suplimentară deasupra portativului în cheia de fa — exact punctul de întâlnire al celor două chei.',
                ],
                practice: { category: 'notes', difficulty: 'easy', label: 'Note pe Portativ · Ușor' },
                quiz: [
                    {
                        question: 'Câte linii și spații are un portativ muzical?',
                        choices: ['4 linii, 5 spații', '5 linii, 4 spații', '6 linii, 5 spații', '5 linii, 5 spații'],
                        correctIndex: 1,
                        explanation: 'Un portativ standard are 5 linii și 4 spații între ele.',
                    },
                    {
                        question: 'Ce formează liniile cheii de sol (de jos în sus) prin mnemotehnică?',
                        choices: ['Fa-La-Do-Mi', 'Mi-Sol-Si-Re-Fa (Every Good Boy Does Fine)', 'La-Do-Mi-Sol', 'Sol-Si-Re-Fa-La'],
                        correctIndex: 1,
                        explanation: 'Liniile cheii de sol de jos în sus sunt Mi-Sol-Si-Re-Fa, reținute cu „Every Good Boy Does Fine".',
                    },
                    {
                        question: 'La ce servesc liniile suplimentare?',
                        choices: [
                            'Decorarea portativului',
                            'Extinderea portativului pentru a nota sunete deasupra sau dedesubtul intervalului normal',
                            'Indicarea tempo-ului',
                            'Marcarea armurii',
                        ],
                        correctIndex: 1,
                        explanation: 'Liniile suplimentare sunt linii scurte extra care extind portativul pentru notele prea înalte sau prea joase pentru a încăpea pe cele cinci linii obișnuite.',
                    },
                    {
                        question: 'Unde se află Do din mijloc față de portativele în cheile de sol și fa?',
                        choices: [
                            'La mijlocul portativului în cheia de sol',
                            'Pe o linie suplimentară sub cheia de sol / pe o linie suplimentară deasupra cheii de fa',
                            'Nu poate fi notat în niciuna din chei',
                            'Pe linia de sus a portativului în cheia de fa',
                        ],
                        correctIndex: 1,
                        explanation: 'Do din mijloc se află exact la punctul de întâlnire al celor două chei — o linie suplimentară sub cheia de sol, una deasupra cheii de fa.',
                    },
                ],
            },
            {
                id: 'staff-note-names',
                title: 'Numele Notelor pe Portativ',
                summary: 'Construind viteză la citirea notelor, inclusiv în diferite armuri.',
                content: [
                    'A citi fluid înseamnă a recunoaște instantaneu numele literei unei note, fără a număra liniile față de un punct de referință de fiecare dată. Aceasta vine din repetiție — exersând note aleatoare pe întreg intervalul unei chei până când asocierea poziție-literă devine automată.',
                    'O armură schimbă cum este ortografiată o literă, nu unde se află pe portativ. Un Fa pe portativ este tot pe aceeași linie sau spațiu în orice tonalitate — dar într-o tonalitate cu Fa♯ în armura sa, acea aceeași poziție se citește și se cântă ca Fa♯, nu ca Fa simplu.',
                    'Notele pe linii suplimentare sunt de obicei cele mai lente la citit fluid, pur și simplu pentru că apar mai rar. Exersarea deliberată a notelor de deasupra și dedesubtul portativului (nu numai a celor comode din interiorul portativului) închide cel mai rapid acel deficit.',
                ],
                practice: { category: 'notes', difficulty: 'hard', label: 'Note pe Portativ · Greu' },
                quiz: [
                    {
                        question: 'Ce schimbă o armură despre poziția unei note pe portativ?',
                        choices: [
                            'Poziția sa de linie sau spațiu',
                            'Nimic despre poziție — schimbă cum este ortografiată/cântată acea poziție (ex. Fa vs Fa♯)',
                            'Elimină complet nota de pe portativ',
                            'Afectează numai notele de pe linii suplimentare',
                        ],
                        correctIndex: 1,
                        explanation: 'O armură aplică un accident la fiecare instanță a unei anumite linii/spații, fără a-i muta poziția.',
                    },
                    {
                        question: 'De ce notele de pe linii suplimentare sunt de obicei cele mai lente la citit fluid?',
                        choices: [
                            'Sunt mai greu de calculat matematic',
                            'Apar mai rar, deci există mai puțină repetiție de practică în mod implicit',
                            'Nu au nume de litere',
                            'Se folosesc numai în cheia de fa',
                        ],
                        correctIndex: 1,
                        explanation: 'Expunerea mai rară înseamnă recunoaștere mai puțin automată — practica extra deliberată închide acel deficit.',
                    },
                    {
                        question: 'Care este cel mai eficient mod de a construi viteză fluentă la cititul la prima vedere?',
                        choices: [
                            'Memorând o singură piesă',
                            'Exersare repetată pe note aleatoare pe întreg intervalul unei chei',
                            'Evitând liniile suplimentare',
                            'Exersând numai în Do major',
                        ],
                        correctIndex: 1,
                        explanation: 'Exersarea largă și repetată construiește recunoașterea instantă poziție-literă pe care cititul fluid o necesită.',
                    },
                    {
                        question: 'Dacă o armură are Fa♯, cum se citește o notă pe linia de Fa?',
                        choices: ['Ca Fa♯', 'Ca Fa simplu', 'Ca Fa♭', 'Este omisă complet'],
                        correctIndex: 0,
                        explanation: 'Fiecare Fa din acea tonalitate este automat citit și cântat ca Fa♯ datorită armurii, indiferent de octavă.',
                    },
                ],
            },
            {
                id: 'fretboard-notes',
                title: 'Găsirea Notelor pe Grifă',
                summary: 'Acordajul standard, fretele ca semitonuri și octava la frета a 12-a.',
                content: [
                    'Acordajul standard de chitară, de la coarda joasă la cea înaltă, este Mi-La-Re-Sol-Si-Mi. Acordajul standard de bas cu 4 corzi este Mi-La-Re-Sol — aceleași ca cele patru corzi inferioare ale chitarei, doar o octavă mai jos.',
                    'Fiecare fretă ridică sunetul cu exact un semiton, aceeași unitate pe care ai învățat-o la intervale. Asta înseamnă că abilitățile de numire a notelor din cititul la prima vedere și antrenamentul auditiv se transferă direct: numărând fretele numeri semitonuri de la denumirea corzii libere.',
                    'Freta a 12-a este mereu aceeași notă ca coarda liberă, o octavă mai sus — un rezultat direct al faptului că o octavă are 12 semitonuri. Asta face din freta a 12-a un punct de ancorare de încredere: odată ce știi corzile libere, știi deja întregul rând de la freta a 12-a.',
                ],
                practice: { category: 'guitar', difficulty: 'medium', label: 'Grifă Chitară · Mediu' },
                quiz: [
                    {
                        question: 'Care este acordajul standard de chitară, de la coarda cea mai joasă la cea mai înaltă?',
                        choices: ['Mi-La-Re-Sol-Si-Mi', 'Mi-La-Re-Sol-Do-Fa', 'Re-La-Re-Sol-Si-Mi', 'Mi-Si-Sol-Re-La-Mi'],
                        correctIndex: 0,
                        explanation: 'Acordajul standard de jos în sus este Mi-La-Re-Sol-Si-Mi.',
                    },
                    {
                        question: 'Cu cât ridică sunetul fiecare fretă?',
                        choices: ['Un ton întreg', 'Un semiton', 'O terță mare', 'Variază în funcție de coardă'],
                        correctIndex: 1,
                        explanation: 'Fiecare fretă este exact cu un semiton mai înaltă decât precedenta, pe orice coardă.',
                    },
                    {
                        question: 'Ce notă obții la freta a 12-a a oricărei corzi?',
                        choices: [
                            'O notă aleatoare în funcție de coardă',
                            'Aceeași notă ca și coarda liberă, o octavă mai sus',
                            'Mereu un Mi',
                            'Nota la o cvintă justă deasupra corzii libere',
                        ],
                        correctIndex: 1,
                        explanation: '12 frete = 12 semitonuri = exact o octavă, deci freta a 12-a se potrivește mereu cu numele corzii libere.',
                    },
                    {
                        question: 'Acordajul standard de bas cu 4 corzi se potrivește cu ce patru corzi de chitară?',
                        choices: [
                            'Cele patru corzi superioare de chitară',
                            'Cele patru corzi inferioare de chitară (o octavă mai jos)',
                            'Nu are nicio legătură cu acordajul de chitară',
                            'Toate cele șase corzi de chitară',
                        ],
                        correctIndex: 1,
                        explanation: 'Basul Mi-La-Re-Sol se potrivește cu cele patru corzi inferioare de chitară, dar acordat cu o octavă mai jos.',
                    },
                ],
            },
        ],
    },
    {
        id: 'advanced-harmony',
        title: 'Armonie Avansată',
        description: 'Dincolo de diatonic: împrumut cromatic, dominante secundare și vocabularul jazz construit pe acorduri extinse.',
        lessons: [
            {
                id: 'secondary-dominants',
                title: 'Dominante Secundare',
                summary: 'Împrumutând V7 al unui V7 — tonicizând un acord altul decât tonica.',
                content: [
                    'O dominantă secundară este un acord de dominantă septimă care rezolvă la un acord altul decât tonica, tratând temporar acel acord ca și cum ar fi propriul său mic „I". Cea mai frecventă este V7/V — dominanta dominantei — construită cu o cvintă deasupra acordului V și rezolvând în V însuși.',
                    'Deoarece V7/V împrumută terța sa din afara tonalității principale (în Do major, V7/V este Re7, care conține Fa♯ — absent din gama Do major), injectează o sclipire de cromatism fără a ieși complet din tonalitate. Urechea o aude ca o atracție suplimentară spre orice acord urmează.',
                    'Orice acord diatonic cu excepția tonicii și a triadei sensibilei poate fi tonicizat în acest mod: V7/vi rezolvă la vi, V7/ii rezolvă la ii, și așa mai departe. Lanțuri de dominante secundare — V7/ii ducând la V7/V ducând la V ducând la I — tonicizează un acord după altul pe drumul acasă, la fel cum un jazzman se apropie de o notă-țintă pas cu pas.',
                ],
                practice: { category: 'progressions', difficulty: 'expert', label: 'Progresii de Acorduri · Expert' },
                quiz: [
                    {
                        question: 'Ce face o dominantă secundară?',
                        choices: [
                            'Înlocuiește permanent tonica',
                            'Rezolvă temporar la un acord altul decât tonica, împrumutând atracția dominantă-tonică',
                            'Elimină necesitatea armurii',
                            'Există numai în tonalități minore',
                        ],
                        correctIndex: 1,
                        explanation: 'O dominantă secundară tratează temporar un acord non-tonic ca și cum ar fi „I", rezolvând în el la fel cum V7 rezolvă în I.',
                    },
                    {
                        question: 'În Do major, V7/V este ce acord?',
                        choices: ['Sol7', 'Re7', 'La7', 'Do7'],
                        correctIndex: 1,
                        explanation: 'V7/V este construit cu o cvintă deasupra lui V (Sol), aterizând pe Re — deci V7/V este Re7, care rezolvă în Sol.',
                    },
                    {
                        question: 'De ce sună V7/V cromatic, chiar dacă rezolvă la un acord V diatonic?',
                        choices: [
                            'Conține o notă (terța sa majoră) din afara gamei tonalității principale',
                            'Elimină complet nota de bas',
                            'Se cântă mereu în afara tempo-ului',
                            'Nu are terță',
                        ],
                        correctIndex: 0,
                        explanation: 'Terța lui V7/V vine din afara gamei majore principale, ceea ce îi conferă exact acea sclipire de culoare.',
                    },
                    {
                        question: 'Ce realizează un lanț ca V7/ii - V7/V - V - I?',
                        choices: [
                            'Tonicizează tonica însăși, repetat',
                            'Tonicizează o secvență de acorduri diatonice, abordate câte unul',
                            'Nimic — lanțurile de dominante secundare nu apar în muzica reală',
                            'Funcționează numai pe triada sensibilei',
                        ],
                        correctIndex: 1,
                        explanation: 'Fiecare dominantă secundară din lanț tonicizează temporar acordul chiar înainte de rezolvarea sa finală la I.',
                    },
                ],
            },
            {
                id: 'modal-interchange',
                title: 'Schimb Modal și Acorduri Împrumutate',
                summary: 'Ajungând în minorul paralel pentru culoare.',
                content: [
                    'Schimbul modal (numit și „acorduri împrumutate") înseamnă folosirea temporară a unui acord din tonalitatea minoră paralelă într-o progresie de major, sau invers. Do major și Do minor împart aceeași tonică dar au a 3-a, a 6-a și a 7-a treaptă diferite, deci împrumutând se schimbă acele note minore pentru câteva timpi înainte de a reveni la sunetul major.',
                    'Cele două acorduri împrumutate mai frecvente sunt iv minor (în loc de IV major) și ♭VI / ♭VII, ambele construite pe trepte alterate din minorul paralel. iv minor dă o întoarcere amară-dulce, melancolică pe care IV major nu o poate oferi; ♭VI-♭VII-I este o mișcare descendentă iubită de rock și compozitorii de muzică de film pentru că sună atât surprinzător cât și inevitabil.',
                    'Acordurile împrumutate funcționează deoarece urechea ascultătorului percepe în continuare tonica tonalității principale ca ancoră — acordul împrumutat este o deviere scurtă, nu o schimbare completă de tonalitate. Asta separă schimbul modal de modulație: tonica nu se mișcă niciodată, numai gama care furnizează un acord sau două o face.',
                ],
                practice: { category: 'progressions', difficulty: 'expert', label: 'Progresii de Acorduri · Expert' },
                quiz: [
                    {
                        question: 'Ce este schimbul modal?',
                        choices: [
                            'Schimbarea permanentă a tonalității',
                            'Împrumutarea unui acord din tonalitatea majoră sau minoră paralelă, în timp ce tonica rămâne aceeași',
                            'Cântarea aceluiași acord de două ori la rând',
                            'Eliminarea tuturor acordurilor minore dintr-o tonalitate majoră',
                        ],
                        correctIndex: 1,
                        explanation: 'Tonica rămâne fixă; numai un acord sau două împrumută notele din gama paralelă.',
                    },
                    {
                        question: 'Care este acordul împrumutat cel mai frecvent folosit în locul IV major?',
                        choices: ['iv minor, împrumutat din minorul paralel', 'V major', 'vii° diminuat', 'II major'],
                        correctIndex: 0,
                        explanation: 'iv minor (din tonalitatea minoră paralelă) dă o culoare amară-dulce pe care IV major nu o are.',
                    },
                    {
                        question: '♭VI și ♭VII sunt împrumutate din:',
                        choices: [
                            'Dominanta relativei minore',
                            'Tonalitatea minoră paralelă',
                            'O tonalitate complet diferită',
                            'Numai din gama majoră armonică',
                        ],
                        correctIndex: 1,
                        explanation: 'Ambele acorduri sunt construite pe trepte alterate preluate din tonalitatea minoră paralelă.',
                    },
                    {
                        question: 'Ce diferențiază schimbul modal de o modulație completă?',
                        choices: [
                            'Schimbul modal mișcă tonica; modulația nu',
                            'Tonica rămâne fixă în schimbul modal — numai un acord sau două împrumută din gama paralelă',
                            'Sunt același lucru',
                            'Schimbul modal apare numai în jazz',
                        ],
                        correctIndex: 1,
                        explanation: 'Modulația mișcă tonica la o nouă tonalitate; schimbul modal ține tonica fixă și împrumută temporar.',
                    },
                ],
            },
            {
                id: 'extended-chords',
                title: 'Acorduri Extinse: None, Undecime și Terțdecime',
                summary: 'Stivuind dincolo de septimă pentru o armonie mai densă, mai jazz.',
                content: [
                    'Acordurile extinse continuă stivuirea de terțe dincolo de septimă: o nonă adaugă a 2-a treaptă a gamei cu o octavă mai sus (0-4-7-10-14 pentru o nonă de dominantă), o undecimă adaugă a 4-a treaptă (0-4-7-10-14-17), iar o terțdecimă adaugă a 6-a treaptă (0-4-7-10-14-17-21). Fiecare extensie adaugă un strat de culoare suplimentar fără a schimba rolul funcțional de bază al acordului.',
                    'În practică, stivele complete sunt rare — cvinta este deseori omisă, iar pe un acord de undecimă terța majoră este frecvent eliminată și ea, deoarece se ciocnește cu undecima la un semiton distanță. Ceea ce contează pentru ureche este extensia de sus: o nonă sună luxuriant, o undecimă sună dens și aproape cluster-like, iar o terțdecimă sună ca întreg seria armonică stivuită odată.',
                    'Acordurile de dominantă extinsă sunt sunetul caracteristic al jazzului: un V7 simplu rezolvând la I este funcțional dar simplu, în timp ce V9, V11 sau V13 adaugă aceeași atracție cu culoare suplimentară — de aceea pianele și chitarele de comping ajung constant la ele în loc de triade simple sau acorduri de septimă.',
                ],
                practice: { category: 'chords', difficulty: 'expert', label: 'ID Acorduri · Expert' },
                quiz: [
                    {
                        question: 'Ce notă adaugă un acord de nonă deasupra unui acord de septimă?',
                        choices: ['A 2-a treaptă a gamei, o octavă mai sus', 'Fundamentala din nou', 'Cvinta dublată', 'A 6-a treaptă'],
                        correctIndex: 0,
                        explanation: 'O nonă este a 2-a treaptă a gamei ridicată cu o octavă, stivuită deasupra acordului de septimă existent.',
                    },
                    {
                        question: 'De ce este terța deseori omisă dintr-un vocing de undecimă?',
                        choices: [
                            'Nu este necesară pentru ca acordul să aibă o fundamentală',
                            'Deoarece se ciocnește — se află la un semiton de undecimă',
                            'Acordurile de undecimă nu au niciodată o terță în niciun vocing',
                            'Pentru a face acordul mai puternic',
                        ],
                        correctIndex: 1,
                        explanation: 'Terța majoră se află la un semiton sub undecimă, creând o ciocnire pe care mulți jucători o evită eliminând terța.',
                    },
                    {
                        question: 'La vocingul unui acord extins dens pe un instrument real, ce notă este eliminată de obicei prima?',
                        choices: ['Fundamentala', 'Cvinta', 'Nona', 'Septima'],
                        correctIndex: 1,
                        explanation: 'Cvinta adaugă cea mai puțină culoare esențială, deci este prima notă tăiată când un vocing trebuie simplificat.',
                    },
                    {
                        question: 'De ce muzicienii jazz preferă V9/V11/V13 în loc de un simplu V7?',
                        choices: [
                            'Nu au nicio funcție de dominantă',
                            'Adaugă aceeași atracție de rezolvare ca V7 plus culoare armonică suplimentară',
                            'Sunt mai ușor de cântat',
                            'Elimină complet necesitatea terței',
                        ],
                        correctIndex: 1,
                        explanation: 'Extensiile mențin aceeași funcție de dominantă adăugând culoare mai bogată și mai densă deasupra.',
                    },
                ],
            },
            {
                id: 'tritone-sub-turnarounds',
                title: 'Substituția de Triton și Turnarounduri Jazz',
                summary: 'Schimbând o dominantă cu dominanta aflată la un triton distanță.',
                content: [
                    'Orice acord de dominantă septimă poate fi înlocuit de un alt acord de dominantă septimă construit la un triton (șase semitonuri) distanță — o mișcare numită substituție de triton. Cele două acorduri împărtășesc același triton între terța și septima lor (doar inversat), deci substitutul rezolvă în continuare convingător, dar basul se mișcă acum o jumătate de ton în jos spre acordul următor în loc de o cvintă.',
                    'Într-un ii-V-I, schimbând V7 cu substitutul său de triton (notat subV7, ♭II7) transformă linia de bas într-o descendentă cromatică fluentă: ii - subV7 - I în loc de ii - V - I. Această mișcare de bas la jumătate de ton este unul dintre cele mai recognoscibile trucuri de reharmonizare din jazz.',
                    'Un turnaround este o scurtă progresie, de obicei la finalul unei fraze sau coruri, care conduce înapoi la începutul formei — clasic I-vi-ii-V. Substituția de triton și dominantele secundare sunt ambele moduri frecvente de a „condimenta" un turnaround simplu, stivuind mai multă mișcare cromatică în aceleași câteva măsuri fără a pierde funcția de bază.',
                ],
                practice: { category: 'progressions', difficulty: 'expert', label: 'Progresii de Acorduri · Expert' },
                quiz: [
                    {
                        question: 'Ce definește o substituție de triton?',
                        choices: [
                            'Înlocuirea unui acord de dominantă septimă cu un alt acord de dominantă septimă la un triton distanță',
                            'Înlocuirea unui acord major cu un acord minor',
                            'Eliminarea completă a acordului dominant',
                            'Dublarea fundamentalei acordului V',
                        ],
                        correctIndex: 0,
                        explanation: 'Dominanta substitut se află la un triton (șase semitonuri) față de original, împărtășind notele sale cheie de tensiune.',
                    },
                    {
                        question: 'De ce o substituție de triton rezolvă totuși convingător?',
                        choices: [
                            'Împărtășește același triton (terța și septima, inversate) cu acordul pe care îl înlocuiește',
                            'Nu are septimă',
                            'Se cântă mereu în tăcere',
                            'Schimbă permanent tonalitatea',
                        ],
                        correctIndex: 0,
                        explanation: 'Terța și septima unui acord de dominantă septimă sunt septima și terța (inversate) ale acordului la un triton distanță — tensiunea centrală se transferă.',
                    },
                    {
                        question: 'În ii - subV7 - I, cum se mișcă basul în tonică?',
                        choices: ['O cvintă în sus', 'O jumătate de ton în jos', 'O terță mare în sus', 'Nu se mișcă'],
                        correctIndex: 1,
                        explanation: 'Substitutul de triton se află la un semiton deasupra tonicii, deci rezolvând în I este o descendentă cromatică fluentă.',
                    },
                    {
                        question: 'Ce este un turnaround?',
                        choices: [
                            'Un exercițiu de gamă',
                            'O scurtă progresie la finalul unei fraze care conduce înapoi la începutul formei',
                            'Un tip de armură',
                            'Un tipar ritmic exclusiv',
                        ],
                        correctIndex: 1,
                        explanation: 'Clasic I-vi-ii-V, un turnaround pregătește revenirea la începutul formei, deseori ornat cu substituții cromatice.',
                    },
                ],
            },
        ],
    },
];
